server:
  port: 8081

spring:
  application:
    name: student-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


















# management:
#   endpoints:
#     web:
#       exposure:
#         include: health
#     health:
#       show-details: always
